import Head from "next/head";
import axios from "axios";

import Layout from "@/components/layout";
import BurgerList from "@/components/burger-list";
import Paginator from "@/components/paginator";
import { GetServerSideProps } from "next";
import { BurgersPageData } from ".";

type BurgerPageProps = {
  data: BurgersPageData;
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await axios.get(
    `http://127.0.0.1:8080/burger?page=${context.params?.id}`
  );
  const data = res.data;

  return {
    props: { data },
  };
};

const BurgerPage = ({ data }: BurgerPageProps) => {
  return (
    <>
      <Head>
        <title>pian-next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex justify-center w-full">
          <BurgerList data={data.Burgers} />
        </div>
        <div>
          <Paginator pageData={data.PageData} />
        </div>
      </Layout>
    </>
  );
};

export default BurgerPage;
