import Head from "next/head";
import Layout from "@/components/layout";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <p className="text-2xl">pian next</p>
      </Layout>
    </>
  );
};

export default Home;
