import Head from "next/head";
import axios from "axios";

import Layout from "@/components/layout";
import { Burger, PageData } from "@/types/burger";
import BurgerList from "@/components/burger-list";

export type BurgersPageData = {
  Burgers: Burger[];
  PageData: PageData;
};

type HomeProps = {
  data: BurgersPageData;
};

export async function getServerSideProps() {
  const res = await axios.get(`http://127.0.0.1:8080/burger`);
  const data = res.data;

  return {
    props: { data },
  };
}

const Home = ({ data }: HomeProps) => {
  return (
    <>
      <Head>
        <title>pian-next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex justify-center w-full">
          <BurgerList data={data} />
        </div>
      </Layout>
    </>
  );
};

export default Home;
